FROM fedora:44

ARG USERNAME=dev
ARG UID=1000
ARG GID=1000

RUN dnf install -y --setopt=install_weak_deps=False \
        ca-certificates curl git sudo \
        just make \
        golang \
        nodejs npm \
        firefox \
        shadow-utils \
    && dnf clean all

RUN groupadd --gid ${GID} ${USERNAME} \
    && useradd --uid ${UID} --gid ${GID} -m -s /bin/bash -G wheel ${USERNAME} \
    && echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${USERNAME} \
    && install -d -o ${UID} -g ${GID} /home/${USERNAME}/.config

ENV GOBIN=/usr/local/bin
ENV GOTOOLCHAIN=auto
RUN GOPROXY=direct go install github.com/tbocek/codehalter@latest

RUN go install golang.org/x/tools/gopls@latest

USER ${USERNAME}
