FROM alpine:3.23

ARG USERNAME=dev
ARG UID=1000
ARG GID=1000

RUN apk add --no-cache \
        ca-certificates curl git sudo \
        bash shadow \
        just make build-base \
        go \
        nodejs npm \
        firefox-esr

RUN groupadd --gid ${GID} ${USERNAME} \
    && useradd --uid ${UID} --gid ${GID} -m -s /bin/bash -G wheel ${USERNAME} \
    && echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${USERNAME} \
    && install -d -o ${UID} -g ${GID} /home/${USERNAME}/.config

ENV GOBIN=/usr/local/bin
ENV GOTOOLCHAIN=auto
RUN GOPROXY=direct go install github.com/tbocek/codehalter@latest

RUN go install golang.org/x/tools/gopls@latest

USER ${USERNAME}
